name: Development

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # container: denoland/deno:1.29.3

    # Service containers to run with the job
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      # - name: Verify formatting
      #   run: deno fmt --check
      # - name: Run model method unit tests
      #   run: deno test -A --no-check ./Test/model_test.ts
      # - name: Run model method integration tests
      #   env:
      #     TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
      #     ENVIRONMENT: test
      #   run: deno test -A --no-check ./Test/model_integration_tests/
      - name: Run model method integration tests
        env:
          ENVIRONMENT: test
          TEST_DB_URI: postgresql://postgres:postgres@localhost:5432
        run: deno test -A --no-check ./Test/model_integration_tests/
