name: Development

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # Docker Hub image that the job executes in
    container: denoland/deno:alpine

    # Service containers to run with job 'test'
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Verify formatting
        run: deno fmt --check
      - name: Run model method unit tests
        run: deno test -A --no-check ./Test/model_test.ts
      - name: Run model method integration tests
        run: deno test -A --no-check ./Test/model_integration_tests/
